### ISSUE TITLE
不知道是不是自己的问题

### ISSUE THREAD

**Issue by dawnerio** [CharAct3/nav-new-tab#5]
无法自动加载favicon，停用了其他插件还是会，不知道是不是chrome的问题
![newtab.jpg](https://i.loli.net/2020/06/14/6u5QW2FhT9gUGVn.jpg)

**Comment by CharAct3** [comment]
因为是用浏览器的 API 去读取 favicon 的 URL 的，添加新 URL 的时候要等浏览器加载出 favicon，否则读到的就是 undefined
![image](https://user-images.githubusercontent.com/15243594/85242132-bbe67180-b470-11ea-9287-15a7c2edf7bd.png)
